language: node_js
sudo: 'false'
node_js: node
dist: trusty
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: '${NPM_EMAIL}'
  api_key: '${NPM_TOKEN}'
  skip_cleanup: true
  on:
    branch: master
    tags: true
